name: Build
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
